version: "2"
services:
  ergastdb:
    container_name: ergastdb
    build: ergastdb/
    environment:
      MYSQL_ROOT_PASSWORD: f1
      MYSQL_DATABASE: ergastdb
    expose:
      - "3306"

  web:
    container_name: ergastapi
    build: lamp/
    ports:
      - '8000:80'
    volumes:
      - ./webroot:/var/www/html
      - ./php/api:/php/api
      - ./logs:/var/log/apache2
    links:
      - ergastdb:ergastdb

# docker compose up --build -d
# docker compose build --force-rm
# docker compose up -d
